source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'PLMediaStreamingKitDemo' do
  pod "PLMediaStreamingKit", :path => "../"
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Masonry'
  pod 'BlocksKit'
  pod 'WeiboSDK'
  pod 'Toast', '~> 4.0.0'
  pod 'Bugly', '2.5.0'
  pod 'KVOController', '1.2.0'
  pod 'Mantle', '2.1.0'
  pod 'AFNetworking', '~> 3.0'
  pod 'SSZipArchive'
  pod 'ZLPhotoBrowser'
  pod 'DGActivityIndicatorView'
end
